"""Programmatic report generation from result artifacts.

Every number that appears in ``results/report.md`` and in the generated block of
``README.md`` is rendered from the JSON artifacts on disk by this module. The
hand-written README table that disagreed with ``results/multi_seed_results.json``
was the root cause of the v1 reporting discrepancy, so the numbers are no longer
maintained by hand.

Usage::

    python -m rsi_framework.reporting --results results --readme README.md --update
    python -m rsi_framework.reporting --results results --readme README.md --check
"""

from __future__ import annotations

import argparse
import json
import platform
import subprocess
import sys
from pathlib import Path

from .core import EXPERIMENT_VERSION, LEGACY_ROLLBACK_DECISION, ROLLBACK_DECISION, config_hash, dataset_hash

README_BEGIN = "<!-- BEGIN GENERATED: empirical results (do not edit by hand) -->"
README_END = "<!-- END GENERATED: empirical results -->"

#: Files whose bytes are a pure function of the config and seed. Only these may
#: be described as byte-reproducible; see ``REPRODUCIBILITY_NOTE``.
DETERMINISTIC_ARTIFACTS = ("first_run.json", "history.jsonl", "metrics.csv", "progress.svg")

REPRODUCIBILITY_NOTE = (
    "Byte equality is claimed only for "
    + ", ".join(f"`{name}`" for name in DETERMINISTIC_ARTIFACTS)
    + ". They contain no timestamp and no runtime measurement. "
    "`multi_seed_results.json`, `multi_seed_metrics.csv`, `ablation_results.json` and "
    "`ablation_metrics.csv` embed `runtime_seconds` and `report.md` embeds those runtimes, "
    "so they are numerically reproducible but not byte-reproducible. `provenance.json` "
    "records the checkout state and is deliberately excluded from the claim."
)


def load_artifacts(results_dir: Path) -> dict:
    """Load whatever result artifacts exist in ``results_dir``."""
    artifacts: dict = {}
    for key, name in (
        ("first_run", "first_run.json"),
        ("multi_seed", "multi_seed_results.json"),
        ("ablation", "ablation_results.json"),
        ("provenance", "provenance.json"),
    ):
        path = Path(results_dir) / name
        if path.exists():
            artifacts[key] = json.loads(path.read_text())
    return artifacts


def _fmt(value: float, nd: int = 3) -> str:
    return f"{value:.{nd}f}"


def _accuracy_cell(entry: dict, field: str = "accuracy") -> str:
    if field == "accuracy" and "accuracy" in entry:
        return f"{entry['accuracy']:.3f} ({entry.get('correct', '?')}/{entry.get('total', '?')})"
    return _fmt(entry[field])


def render_report(artifacts: dict) -> str:
    """Render the complete human-readable report from loaded artifacts."""
    first = artifacts.get("first_run")
    multi = artifacts.get("multi_seed")
    ablation = artifacts.get("ablation")
    provenance = artifacts.get("provenance", {})

    lines: list[str] = [
        "# RSI Experimental Framework — Empirical Report",
        "",
        "> Generated by `python -m rsi_framework.reporting` from the JSON artifacts in "
        "`results/`. Do not edit by hand; edit the renderer and regenerate.",
        "",
        f"**Experiment version**: `{EXPERIMENT_VERSION}` "
        "(token matching: `safe` no longer matches inside `unsafe`, `clear` inside `unclear`)",
        "",
    ]

    lines.extend([
        "## 0. Provenance and Scope",
        "",
        f"- Source commit at generation time: `{provenance.get('source_commit', 'unknown')}`",
        f"- Working tree dirty at generation time: `{provenance.get('source_dirty', 'unknown')}` "
        f"({provenance.get('source_dirty_file_count', '?')} changed paths, listed in `provenance.json`; "
        "this normally includes the artifacts written by this very run)",
        f"- Run command: `{provenance.get('command', 'unknown')}`",
        f"- Config hash: `{provenance.get('config_hash', first.get('config_hash', 'unknown') if first else 'unknown')}`",
        f"- Dataset hash: `{provenance.get('dataset_hash', first.get('dataset_hash', 'unknown') if first else 'unknown')}`",
        f"- Python: `{provenance.get('python', platform.python_version())}`",
        "",
        "**What the numbers are.** A deterministic keyword-policy harness with no model weights and "
        "no LLM calls (`method_label: HARNESS_BASELINE_NOT_LLM`). Accuracy is the fraction of examples "
        "whose label the policy predicts correctly. `mean ± std` is the arithmetic mean and the "
        "*sample* standard deviation (`ddof=1`) over the listed seeds.",
        "",
        "**What the numbers are not.** They are not evidence of self-improvement, reasoning, or "
        "generalization. The task is a 32-sentence synthetic lexical pool and every seed re-shuffles "
        "*the same pool*, so the runs are replays of one toy dataset, not independent real-world samples.",
        "",
        "**Decision labels are operational.** `improvement` / `flat` / `regression` are defined by a "
        "single held-out comparison with a fixed tolerance for one run. They are not a significance "
        "test, a confidence interval, an equivalence proof, or an estimate of an effect size.",
        "",
    ])

    if first:
        lines.extend([
            "## 1. Single Run (seed " + str(first["seed"]) + ")",
            "",
            f"Experiment version `{first.get('experiment_version', EXPERIMENT_VERSION)}`; "
            f"config `{first.get('config_hash', 'n/a')}`; dataset `{first.get('dataset_hash', 'n/a')}`.",
            "",
            "| Split | n | Baseline | Final policy | Role |",
            "|---|---:|---|---|---|",
            f"| Train | {first['splits']['train']} | {_accuracy_cell(first['baseline']['train'])} | "
            f"{_accuracy_cell(first['final']['train'])} | Used for selection |",
            f"| Dev | {first['splits']['dev']} | {_accuracy_cell(first['baseline']['dev'])} | "
            f"{_accuracy_cell(first['final']['dev'])} | Used for selection and rejection |",
            f"| Held-out | {first['splits']['heldout']} | {_accuracy_cell(first['baseline_heldout'])} | "
            f"{_accuracy_cell(first['final']['heldout'])} | Measured only after selection stops |",
            "",
            f"- Accepted candidate versions **including the baseline**: "
            f"{first['accepted_baseline_included_count']}",
            f"- Accepted **new changes** (baseline excluded): {first['accepted_new_change_count']} "
            f"(`{', '.join(first['accepted_new_changes']) or 'none'}`)",
            f"- Rejected dev regressions: "
            f"{sum(1 for row in first['history'] if row.get('decision') in (ROLLBACK_DECISION, LEGACY_ROLLBACK_DECISION))}",
            f"- Rejected invalid proposals: {first.get('rejected_proposal_count', 0)}",
            f"- Search generations: {len(first['history']) - 1}",
            f"- Final policy hash: `{first['final']['version']}`",
            f"- Reported outcome: **{first['outcome']}** (operational decision rule; see scope above)",
            "",
        ])

    if multi:
        seeds = ", ".join(str(s) for s in multi["seeds"])
        lines.extend([
            "## 2. Multi-Seed Replay (seeds: " + seeds + ")",
            "",
            f"N = {multi['num_runs']} seeds; {multi['train_examples_per_seed']} train / "
            f"{multi['dev_examples_per_seed']} dev / {multi['heldout_examples_per_seed']} held-out "
            "examples per run. `mean ± std` uses the sample standard deviation (`ddof=1`). "
            "Every seed re-shuffles the same 32-row synthetic pool, so these are replays of one toy "
            "dataset rather than independent samples.",
            "",
            "| Seed | Train (n) | Dev (n) | Held-out (n) | Held-out correct | Gain | Rejected regressions | "
            "Accepted incl. baseline | Accepted new | Runtime (s) | Outcome |",
            "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|",
        ])
        for r in multi["runs"]:
            lines.append(
                f"| {r['seed']} | {_fmt(r['final_train_acc'])} ({r['train_total']}) | "
                f"{_fmt(r['final_dev_acc'])} ({r['dev_total']}) | "
                f"{_fmt(r['final_heldout_acc'])} ({r['heldout_total']}) | "
                f"{r['heldout_correct']}/{r['heldout_total']} | {r['heldout_gain']:+.3f} | "
                f"{r['regression_count']} | {r['accepted_baseline_included_count']} | "
                f"{r['accepted_new_change_count']} | {r['runtime_seconds']:.4f} | {r['outcome']} |"
            )
        lines.extend([
            "",
            "### Aggregate (mean ± sample std, ddof=1)",
            f"- Train accuracy (final): {_fmt(multi['train_accuracy']['mean'])} ± "
            f"{_fmt(multi['train_accuracy']['std'])} over N={multi['train_accuracy']['n']} seeds",
            f"- Dev accuracy (final): {_fmt(multi['dev_accuracy']['mean'])} ± "
            f"{_fmt(multi['dev_accuracy']['std'])} over N={multi['dev_accuracy']['n']} seeds",
            f"- Held-out accuracy (final): {_fmt(multi['heldout_accuracy']['mean'])} ± "
            f"{_fmt(multi['heldout_accuracy']['std'])} over N={multi['heldout_accuracy']['n']} seeds, "
            f"each on {multi['heldout_examples_per_seed']} examples",
            f"- Held-out gain: {multi['heldout_gain']['mean']:+.3f} ± {multi['heldout_gain']['std']:.3f}",
            f"- Rejected dev regressions: {multi['regression_count']['mean']:.2f} ± "
            f"{multi['regression_count']['std']:.2f}",
            f"- Accepted versions incl. baseline: {multi['accepted_baseline_included_count']['mean']:.2f} ± "
            f"{multi['accepted_baseline_included_count']['std']:.2f}",
            f"- Accepted new changes: {multi['accepted_new_changes']['mean']:.2f} ± "
            f"{multi['accepted_new_changes']['std']:.2f}",
            "",
            "With 8 held-out examples per run, one example is worth 0.125 accuracy. Differences of one "
            "or two examples are not interpretable as an effect and no claim here should be read as one.",
            "",
        ])

    if ablation:
        lines.extend([
            "## 3. Ablations",
            "",
            f"All modes use seed {ablation['runs'][0]['seed']}, the same dataset hash "
            f"(`{ablation['runs'][0]['dataset_hash']}`) and the same proposal budget "
            f"({ablation['runs'][0]['generations']} generations). Comparability check recorded in the "
            f"artifact: `{ablation.get('comparable_seed_data_budget')}`.",
            "",
            "| Variant | Mechanism switched off | Train | Dev | Held-out | Gain | Rejected regressions | "
            "Accepted new | Outcome |",
            "|---|---|---:|---:|---:|---:|---:|---:|---|",
        ])
        for r in ablation["runs"]:
            lines.append(
                f"| `{r['mode']}` | {r['mechanism']} | {_fmt(r['final_train_acc'])} | "
                f"{_fmt(r['final_dev_acc'])} | {_fmt(r['final_heldout_acc'])} | {r['heldout_gain']:+.3f} | "
                f"{r['regression_count']} | {r['accepted_new_change_count']} | {r['outcome']} |"
            )
        lines.extend([
            "",
            "`ablation_no_selection` is **not** a score-free control: it still selects greedily by train "
            "accuracy, it merely stops consulting dev. `ablation_random_selection` is the genuine "
            "score-free control (seed-controlled random pick, accepted unconditionally).",
            "",
        ])

    lines.extend([
        "## 4. Reproducibility Scope",
        "",
        REPRODUCIBILITY_NOTE,
        "",
        "The unit test `test_deterministic_and_runtime_artifacts_are_separated` runs the experiment twice "
        "and compares both classes of file, so the scope above is enforced, not merely asserted.",
        "",
        "## 5. What the Tests Do and Do Not Establish",
        "",
        "- `test_heldout_data_does_not_affect_selection` is a **scoped invariance check**: on this fixed "
        "synthetic dataset, inverting every held-out label and rewriting every held-out sentence leaves "
        "the recorded selection chain, versions and dev scores unchanged. It is not a mathematical proof "
        "of zero leakage for arbitrary code paths.",
        "- `test_proposal_validation_*` exercises the injected-provider gate on synthetic proposals. It "
        "does not evaluate a language model; no LLM has been run in this repository.",
        "- Passing tests confirm harness mechanics only. They are not confirmation of the research "
        "hypothesis.",
        "",
        f"## 6. Rejected Candidates",
        "",
        "Invalid or out-of-policy proposals are recorded per run under `rejected_proposals` in "
        f"`first_run.json`. Decision labels: `{ROLLBACK_DECISION}` (candidate rejected because dev "
        "regressed; the applied policy state is never mutated, so nothing is rolled back) and "
        f"`{LEGACY_ROLLBACK_DECISION}` (v1 archives only).",
        "",
        "## 7. Limitations",
        "",
        "- Harness baseline only: no weights trained, no LLM called. "
        "`OpenWeightColabL4Stub` is an unwired boundary, not an integration.",
        "- Synthetic 32-sentence lexical pool shared by every seed; no real-world data.",
        "- Held-out split is 8 examples; conclusions must stay proportionate.",
        "- `improvement` / `flat` / `regression` are operational labels, not significance results.",
        "",
    ])
    return "\n".join(lines)


def render_readme_results(artifacts: dict) -> str:
    """Render the README results block (without the begin/end markers)."""
    multi = artifacts.get("multi_seed")
    ablation = artifacts.get("ablation")
    first = artifacts.get("first_run")
    lines: list[str] = []

    if first:
        lines.extend([
            "### 1. Single Run (Seed " + str(first["seed"]) + ")",
            f"- **Method label**: `{first['method_label']}`; experiment version `{first.get('experiment_version', EXPERIMENT_VERSION)}`",
            f"- **Train accuracy**: {_accuracy_cell(first['baseline']['train'])} -> {_accuracy_cell(first['final']['train'])}",
            f"- **Dev accuracy**: {_accuracy_cell(first['baseline']['dev'])} -> {_accuracy_cell(first['final']['dev'])}",
            f"- **Held-out accuracy**: {_accuracy_cell(first['baseline_heldout'])} -> {_accuracy_cell(first['final']['heldout'])}",
            f"- **Outcome**: `{first['outcome']}` ({first['accepted_new_change_count']} accepted new changes, "
            f"{first['accepted_baseline_included_count']} accepted versions including the baseline, "
            f"{sum(1 for row in first['history'] if row.get('decision') in (ROLLBACK_DECISION, LEGACY_ROLLBACK_DECISION))} rejected dev regressions)",
            "",
        ])

    if multi:
        lines.extend([
            "### 2. Multi-Seed Replay (Seeds: " + ", ".join(str(s) for s in multi["seeds"]) + ")",
            f"- **N seeds**: {multi['num_runs']}; **held-out examples per run**: {multi['heldout_examples_per_seed']}; "
            "**std**: sample standard deviation (`ddof=1`)",
            f"- **Train accuracy (final)**: {_fmt(multi['train_accuracy']['mean'])} ± {_fmt(multi['train_accuracy']['std'])}",
            f"- **Dev accuracy (final)**: {_fmt(multi['dev_accuracy']['mean'])} ± {_fmt(multi['dev_accuracy']['std'])}",
            f"- **Held-out accuracy (final)**: {_fmt(multi['heldout_accuracy']['mean'])} ± {_fmt(multi['heldout_accuracy']['std'])}",
            f"- **Held-out gain**: {multi['heldout_gain']['mean']:+.3f} ± {multi['heldout_gain']['std']:.3f}",
            f"- **Rejected dev regressions**: {multi['regression_count']['mean']:.2f} ± {multi['regression_count']['std']:.2f}",
            f"- **Accepted versions including the baseline**: {multi['accepted_baseline_included_count']['mean']:.2f} ± {multi['accepted_baseline_included_count']['std']:.2f}",
            f"- **Accepted new changes (baseline excluded)**: {multi['accepted_new_changes']['mean']:.2f} ± {multi['accepted_new_changes']['std']:.2f}",
            "",
            "All seeds re-shuffle the same 32-row synthetic pool; these are replays of one toy dataset, "
            "not independent real-world samples. `improvement` / `flat` / `regression` are operational "
            "decision labels, not significance results.",
            "",
        ])

    if ablation:
        lines.extend([
            "### 3. Ablations",
            "| Variant | Held-out accuracy | Held-out gain | Accepted new | Outcome |",
            "|---|---:|---:|---:|---|",
        ])
        for r in ablation["runs"]:
            lines.append(
                f"| `{r['mode']}` | {_fmt(r['final_heldout_acc'])} | {r['heldout_gain']:+.3f} | "
                f"{r['accepted_new_change_count']} | {r['outcome']} |"
            )
        lines.append("")
    return "\n".join(lines)


def update_readme(readme_path: Path, artifacts: dict) -> None:
    """Replace the generated block in the README between the marker comments."""
    text = Path(readme_path).read_text()
    if README_BEGIN not in text or README_END not in text:
        raise SystemExit(f"{readme_path}: generated-results markers not found")
    head, rest = text.split(README_BEGIN, 1)
    _, tail = rest.split(README_END, 1)
    block = f"{README_BEGIN}\n{render_readme_results(artifacts).rstrip()}\n{README_END}"
    Path(readme_path).write_text(head + block + tail)


def check_consistency(results_dir: Path, readme_path: Path | None = None) -> list[str]:
    """Return a list of consistency problems (empty means consistent)."""
    problems: list[str] = []
    artifacts = load_artifacts(results_dir)

    report_path = Path(results_dir) / "report.md"
    if not report_path.exists():
        problems.append("results/report.md is missing")
    else:
        expected_report = render_report(artifacts).rstrip() + "\n"
        if report_path.read_text() != expected_report:
            problems.append("results/report.md does not match the renderer output")

    if readme_path is not None:
        readme = Path(readme_path)
        if not readme.exists():
            problems.append(f"{readme} is missing")
        else:
            text = readme.read_text()
            if README_BEGIN not in text or README_END not in text:
                problems.append(f"{readme}: generated-results markers not found")
            else:
                block = text.split(README_BEGIN, 1)[1].split(README_END, 1)[0].strip()
                expected_block = render_readme_results(artifacts).strip()
                if block != expected_block:
                    problems.append(f"{readme}: generated results block is stale")

    # Independent numeric cross-check: every value in the artifacts must appear in
    # the rendered report. This catches a renderer that drops or renames a metric.
    report_text = report_path.read_text() if report_path.exists() else ""
    multi = artifacts.get("multi_seed")
    if multi:
        for key in ("train_accuracy", "dev_accuracy", "heldout_accuracy", "heldout_gain"):
            mean = _fmt(multi[key]["mean"])
            if mean not in report_text:
                problems.append(f"report.md does not contain {key} mean {mean}")
    return problems


def collect_provenance(
    results_dir: Path,
    config: dict,
    examples: list,
    command: str,
    seeds: list[int] | None = None,
) -> dict:
    """Write provenance.json and return it. Not part of the byte-equality claim."""

    def _git(*args: str) -> str:
        try:
            return subprocess.run(
                ["git", *args], capture_output=True, text=True, check=False
            ).stdout.strip()
        except OSError:
            return "unavailable"

    dirty_files = [line for line in _git("status", "--porcelain").splitlines() if line.strip()]
    provenance = {
        "generated_by": "python -m rsi_framework",
        "experiment_version": EXPERIMENT_VERSION,
        "source_commit": _git("rev-parse", "HEAD") or "unavailable",
        "source_dirty": bool(dirty_files),
        "source_dirty_file_count": len(dirty_files),
        "source_dirty_files": dirty_files,
        "command": command,
        "config": config,
        "config_hash": config_hash(config),
        "config_seed": config.get("seed"),
        "seeds": list(seeds) if seeds is not None else [config.get("seed")],
        "dataset_hash": dataset_hash(examples),
        "dataset": {
            "generator": "rsi_framework.core.make_dataset",
            "examples_per_pattern": config.get("examples_per_pattern"),
            "pool_size": len(examples),
            "note": "Same fixed sentence pool for every seed; seeds only re-shuffle it.",
        },
        "splits": {split: sum(e.split == split for e in examples) for split in ("train", "dev", "heldout")},
        "python": platform.python_version(),
        "platform": platform.platform(),
        "note": (
            "Records the checkout state at run time. Deliberately excluded from the "
            "byte-reproducibility claim because the commit and dirty state vary. The dirty list "
            "normally contains the artifacts this run just wrote."
        ),
    }
    Path(results_dir).mkdir(parents=True, exist_ok=True)
    (Path(results_dir) / "provenance.json").write_text(json.dumps(provenance, indent=2, sort_keys=True) + "\n")
    return provenance


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", type=Path, default=Path("results"))
    parser.add_argument("--readme", type=Path, default=Path("README.md"))
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--update", action="store_true", help="regenerate report.md and the README block")
    group.add_argument("--check", action="store_true", help="verify report.md and the README block")
    args = parser.parse_args(list(argv) if argv is not None else None)

    artifacts = load_artifacts(args.results)
    if args.update:
        (args.results / "report.md").write_text(render_report(artifacts).rstrip() + "\n")
        update_readme(args.readme, artifacts)
        print(f"updated {args.results / 'report.md'} and {args.readme}")
        return 0

    problems = check_consistency(args.results, args.readme)
    if problems:
        for problem in problems:
            print(f"INCONSISTENT: {problem}", file=sys.stderr)
        return 1
    print("report.md and README generated block are consistent with results artifacts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
